Use cosmiconfig for config file management
zeplin/cli pull request #48
Opened 2020-12-02 14:03 UTC by Helehelehele

2020-12-02 14:23 UTC, yuqu requested changes
Structure looks OK.

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +    if (discoveredConfigFile === null || discoveredConfigFile === void 0) {
```suggestion
    if (!discoveredConfigFile) {
```

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +    }
This is duplicated, could you move this into a function?

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +         * If no config file was specified by the user, try to discover default configutation
```suggestion
         * If no config file was specified by the user, try to discover default configuration
```
typo

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +            if (defaultConfigFile === null) {
```suggestion
            if (!defaultConfigFile) {
```

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +                throw new Error("Missing configuration file!");
```suggestion
                throw new Error(dedent`
                            Missing configuration file!
                            Please refer to ${chalk.underline`https://zpl.io/connected-components`} to create a configuration file.
                `);
```

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/index.ts
> +    logger.info(`component config files: ${JSON.stringify(componentConfigFiles)}`);
I guess this is leftover from debugging

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +    if (result === null || result.isEmpty) {
```suggestion
    if (!result || result.isEmpty) {
```

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +    logger.info(`Found filepath: ${result?.filepath}`);
Should be deleted

2020-12-02 14:23 UTC, yuqu commented on src/commands/connect/config.ts
> +    logger.info(`${filePath} content: ${JSON.stringify(config)}`);
Should be deleted

2020-12-02 14:23 UTC, yuqu commented on test/connect/config.test.ts
> +const configResourcePath = path.join(process.cwd(), "test", "resources", "config");
```suggestion
const configResourcePath = path.resolve("test", "resources", "config");
```

2020-12-02 16:09 UTC, yuqu requested changes

2020-12-02 16:09 UTC, yuqu commented on test/connect/__snapshots__/config.test.ts.snap
> +exports[`ConfigProcessor when config file options are passed and at least one is invalid fails 1`] = `"Oops! Looks like /Users/mertkizilirmak/projects/cli/test/resources/config/invalid/.zeplin/compon
These type of tests are going to fail on CI and other machines because of the absolute file paths. I wonder if we can easily show a relative path for all cases. If it is not practical, you may use assertion (for example via regex) instead of snapshot.

2020-12-02 16:21 UTC, Helehelehele commented on test/connect/__snapshots__/config.test.ts.snap
> +exports[`ConfigProcessor when config file options are passed and at least one is invalid fails 1`] = `"Oops! Looks like /Users/mertkizilirmak/projects/cli/test/resources/config/invalid/.zeplin/compon
I'll make the change to print out the relative path instead of the absolute path.

2020-12-02 17:25 UTC, yuqu approved these changes
LGTM 🚀

2020-12-02 17:25 UTC, yuqu commented on src/util/file.ts
> +export function transformAbsolutePathToRelativePath(filePath: string): string {
The function works even if it is already relative. We can name it as `transformToRelativePath`

2020-12-03 14:22 UTC, skarahoda approved these changes

2020-12-03 14:22 UTC, skarahoda commented on src/commands/connect/config.ts
> +                throw new Error(dedent`
I didn't know `dedent` 🤯  http://gph.is/2AmePHo

2020-12-03 14:27 UTC, merged