Web auth
zeplin/cli pull request #55
Opened 2020-12-16 13:11 UTC by Helehelehele

JIRA: ZCLI-10

2020-12-21 22:30 UTC, yuqu requested changes

2020-12-21 22:30 UTC, yuqu commented on src/service/auth.ts
> +        authUrl.searchParams.append("scope", "read+write+delete");
```suggestion
        authUrl.searchParams.append("client_id", defaults.api.clientId);
        authUrl.searchParams.append("scope", "read+write+delete");
        authUrl.searchParams.append("redirect_uri", defaults.api.webAuthRedirectURL);
```

`defaults.api.webAuthRedirectURL` should be `process.env.WEB_AUTH_REDIRECT_URI || "http://app.zeplin.io/cliAuthorized"`

2020-12-22 12:43 UTC, Helehelehele commented on test/auth.test.ts
> +            await expect(authenticationService.promptForLogin({ ignoreSaveTokenErrors: true, noBrowser: true }))
Yes, since it wasn't declared as an optional inside params.

2020-12-22 12:51 UTC, yuqu commented on test/auth.test.ts
> +            await expect(authenticationService.promptForLogin({ ignoreSaveTokenErrors: true, noBrowser: true }))
You can make it optional

2020-12-22 15:49 UTC, yuqu approved these changes

2020-12-23 12:53 UTC, skarahoda commented on src/commands/login/server/index.ts
> +        };
```suggestion
        app.get(this.redirectPath, async (req, res, next) => {
            this.accessToken = req.query.access_token;

            if (!this.accessToken) {
                res.status(BAD_REQUEST).json({ error:"No access token" });
            } else {
                res.status(OK).json({ accessToken: this.accessToken });
            }
            await this.stop();
        });
        
        
        export const handleError: ErrorRequestHandler = (err, req, res, next) => {
            if (!res.headersSent) {
                res.status(err?.statusCode ?? INTERNAL_SERVER_ERROR).json({
                    detail: err?.message ?? "Unexpected Error",
                    title: err?.title ?? "Unexpected Error"
                });
            }
            next(err);
        };
```

It's better to keep the error handler more generic by moving stop logic from error handler to controller of redirectPath. We can also implement the function without disabling eslint.

2020-12-23 12:53 UTC, skarahoda commented on src/commands/login/server/index.ts
> +                resolve(this.accessToken);
I think this may resolve the promise twice. When `SIGINT`, the function stops the server and resolve the promise when the server stop, `this.server?.on("close", () => resolve(this.accessToken));` is also triggered and resolve the promise second time.

2020-12-23 12:53 UTC, skarahoda commented on src/service/auth.ts
> +    async authenticate(params?: { requiredScopes: string[]; noBrowser: boolean }): Promise<string> {
```suggestion
    async authenticate({requiredScopes, noBrowser = false}?: { requiredScopes: string[]; noBrowser: boolean } = {}): Promise<string> {
```

To prevent null checks and setting default values in the function body

2020-12-23 13:06 UTC, Helehelehele commented on src/commands/login/server/index.ts
> +                resolve(this.accessToken);
Good catch! 🙌 Instead of resolving in here, I'll just stop the server.

2020-12-23 13:38 UTC, skarahoda approved these changes

2020-12-23 13:38 UTC, merged