Fix auth server CORS headers
zeplin/cli pull request #64
Opened 2020-12-30 13:58 UTC by Helehelehele

Fixes the headers and response to OPTIONS request for CORS pre-flight.

2020-12-30 14:00 UTC, skarahoda approved these changes

2020-12-30 14:02 UTC, yuqu requested changes

2020-12-30 14:02 UTC, yuqu commented on src/server/login-server.ts
> +            res.header("Access-Control-Allow-Headers", "X-Requested-With, Origin, Content-Type, Zeplin-Token");
No need to get Zeplin-Token

2020-12-30 14:07 UTC, Helehelehele commented on src/server/login-server.ts
> +            res.header("Access-Control-Allow-Headers", "X-Requested-With, Origin, Content-Type, Zeplin-Token");
Web app currently sends that in header list with CORS pre-flight request. We can remove it from both sides.

2021-01-08 15:08 UTC, yuqu approved these changes

2021-01-08 15:09 UTC, merged